In [1]:
import numpy as np
import pandas as pd

In [2]:
# Если размерность данных > 2, то используют иерархическую  индексацию (мультииндекс). В один индекс включается несколько уровней
index = [
    ("city1", 2010),
    ("city1", 2020),
    ("city2", 2010),
    ("city2", 2020),
    ("city3", 2010),
    ("city3", 2020),
]
population=[101,201,102,202,103,203]

pop = pd.Series(population, index=index)
print(pop)

(city1, 2010)    101
(city1, 2020)    201
(city2, 2010)    102
(city2, 2020)    202
(city3, 2010)    103
(city3, 2020)    203
dtype: int64


In [3]:
print(pop[[i for i in pop.index if i[1] == 2020]])

(city1, 2020)    201
(city2, 2020)    202
(city3, 2020)    203
dtype: int64


In [4]:
# MultiIndex
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)

city1  2010    101
       2020    201
city2  2010    102
       2020    202
city3  2010    103
       2020    203
dtype: int64


In [5]:
print(pop[:, 2020])

city1    201
city2    202
city3    203
dtype: int64


In [6]:
# В виде DataFrame
pop_df = pop.unstack()
print(pop_df)

       2010  2020
city1   101   201
city2   102   202
city3   103   203


In [7]:
# Обратно из DataFrame
print(pop_df.stack())

city1  2010    101
       2020    201
city2  2010    102
       2020    202
city3  2010    103
       2020    203
dtype: int64


In [8]:
index = [
    ("city1", 2010, 1),
    ("city1", 2010, 2),
    ("city1", 2020, 1),
    ("city1", 2020, 2),
    ("city2", 2010, 1),
    ("city2", 2010, 2),
    ("city2", 2020, 1),
    ("city2", 2020, 2),
    ("city3", 2010, 1),
    ("city3", 2010, 2),
    ("city3", 2020, 1),
    ("city3", 2020, 2),
]
population = [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030]

pop = pd.Series(population, index=index)
print(pop)

(city1, 2010, 1)     101
(city1, 2010, 2)    1010
(city1, 2020, 1)     201
(city1, 2020, 2)    2010
(city2, 2010, 1)     102
(city2, 2010, 2)    1020
(city2, 2020, 1)     202
(city2, 2020, 2)    2020
(city3, 2010, 1)     103
(city3, 2010, 2)    1030
(city3, 2020, 1)     203
(city3, 2020, 2)    2030
dtype: int64


In [9]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)

city1  2010  1     101
             2    1010
       2020  1     201
             2    2010
city2  2010  1     102
             2    1020
       2020  1     202
             2    2020
city3  2010  1     103
             2    1030
       2020  1     203
             2    2030
dtype: int64


In [10]:
print(pop[:, 2010])
print(pop[:, :, 2])

city1  1     101
       2    1010
city2  1     102
       2    1020
city3  1     103
       2    1030
dtype: int64
city1  2010    1010
       2020    2010
city2  2010    1020
       2020    2020
city3  2010    1030
       2020    2030
dtype: int64


In [11]:
# Преобразование в DataFrame
pop_df = pop.unstack()
print(pop_df)

# Обратное преобразование
print(pop_df.stack)

              1     2
city1 2010  101  1010
      2020  201  2010
city2 2010  102  1020
      2020  202  2020
city3 2010  103  1030
      2020  203  2030
<bound method DataFrame.stack of               1     2
city1 2010  101  1010
      2020  201  2010
city2 2010  102  1020
      2020  202  2020
city3 2010  103  1030
      2020  203  2030>


In [12]:
index = [
    ("city1", 2010, 1),
    ("city1", 2010, 2),
    ("city1", 2020, 1),
    ("city1", 2020, 2),
    ("city2", 2010, 1),
    ("city2", 2010, 2),
    ("city2", 2020, 1),
    ("city2", 2020, 2),
    ("city3", 2010, 1),
    ("city3", 2010, 2),
    ("city3", 2020, 1),
    ("city3", 2020, 2),
]
population = [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030]

pop_df = pd.DataFrame(
    {
        "total": pop,
        "something": [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030],
    }
)
print(pop_df)

              total  something
city1 2010 1    101        101
           2   1010       1010
      2020 1    201        201
           2   2010       2010
city2 2010 1    102        102
           2   1020       1020
      2020 1    202        202
           2   2020       2020
city3 2010 1    103        103
           2   1030       1030
      2020 1    203        203
           2   2030       2030


In [13]:
print(pop_df["something"])

city1  2010  1     101
             2    1010
       2020  1     201
             2    2010
city2  2010  1     102
             2    1020
       2020  1     202
             2    2020
city3  2010  1     103
             2    1030
       2020  1     203
             2    2030
Name: something, dtype: int64


In [14]:
index = [
    ("city1", 2010),
    ("city1", 2020),
    ("city2", 2010),
    ("city2", 2020),
    ("city3", 2010),
    ("city3", 2020),
]
population = [101, 1010, 201, 2010, 102, 1020]

pop_df = pd.DataFrame(
    {
        "total": pop,
        "something": [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030],
    }
)

pop_df_1 = pop_df.loc["city1", "something"]
pop_df_2 = pop_df.loc[["city1", "city3"], ["total", "something"]]
pop_df_3 = pop_df.loc[["city1", "city3"], "something"]
print(pop_df_1)
print(pop_df_2)
print(pop_df_3)

2010  1     101
      2    1010
2020  1     201
      2    2010
Name: something, dtype: int64
              total  something
city1 2010 1    101        101
           2   1010       1010
      2020 1    201        201
           2   2010       2010
city3 2010 1    103        103
           2   1030       1030
      2020 1    203        203
           2   2030       2030
city1  2010  1     101
             2    1010
       2020  1     201
             2    2010
city3  2010  1     103
             2    1030
       2020  1     203
             2    2030
Name: something, dtype: int64


In [15]:
# # 1. Разобраться как использовать мультииндексные ключи в данном примере
index = [
    ("city1", 2010),
    ("city1", 2020),
    ("city2", 2010),
    ("city2", 2020),
    ("city3", 2010),
    ("city3", 2020),
]
population = [101, 1010, 201, 2010, 102, 1020]
pop_df = pd.DataFrame(
    {
        "total": pop,
        "something": [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030],
    }
)
pop_df_1 = pop_df.loc["city1", "something"]
pop_df_2 = pop_df.loc[["city1", "city3"], ["total", "something"]]
pop_df_3 = pop_df.loc[["city1", "city3"], "something"]
print(pop_df_1)
print(pop_df_2)
print(pop_df_3)

2010  1     101
      2    1010
2020  1     201
      2    2010
Name: something, dtype: int64
              total  something
city1 2010 1    101        101
           2   1010       1010
      2020 1    201        201
           2   2010       2010
city3 2010 1    103        103
           2   1030       1030
      2020 1    203        203
           2   2030       2030
city1  2010  1     101
             2    1010
       2020  1     201
             2    2010
city3  2010  1     103
             2    1030
       2020  1     203
             2    2030
Name: something, dtype: int64


In [16]:
# Мультииндексы можно создавать как:
# - список массивов, задающих значение индекса на каждом уровне
i1 = pd.MultiIndex.from_arrays(
    [
        [
            "a",
            "a",
            "b",
            "b",
        ],
        [1, 1, 2, 2],
    ]
)
print(i1)

# - список кортежей, задающих значение индекса в каждой точке

i2 = pd.MultiIndex.from_tuples(
    [
        [
            "a",
            "a",
            "b",
            "b",
        ],
        [1, 1, 2, 2],
    ]
)
print(i2)

# - декартово произведение обычных индексов

i3 = pd.MultiIndex.from_product(
    [
        [
            "a",
            "b",
        ],
        [1, 2],
    ]
)
print(i3)

# - описание внутреннего представления: levels, codes

i4 = pd.MultiIndex(
    levels=[
        [
            "a",
            "b",
        ],
        [1, 2],
    ],
    codes=[[0, 0, 1, 1], [0, 1, 0, 1]],  # a a b b  # 1 2 1 2
)
print(i4)

MultiIndex([('a', 1),
            ('a', 1),
            ('b', 2),
            ('b', 2)],
           )
MultiIndex([('a', 'a', 'b', 'b'),
            (  1,   1,   2,   2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [17]:
### Уровням можно задавать названия

data = {
    ("city1", 2010): 100,
    ("city1", 2020): 200,
    ("city2", 2010): 1001,
    ("city2", 2020): 1002,
}
s = pd.Series(data)
print(s)

s.index.names = ["city", "year"]
print(s)

index = pd.MultiIndex.from_product(
    [
        [
            "city1",
            "city2",
        ],
        [2010, 2020],
    ],
    names=["city", "year"],
)
print(index)

columns = pd.MultiIndex.from_product(
    [
        [
            "person1",
            "person2",
            "person3",
        ],
        ["job1", "job2"],
    ],
    names=["worker", "job"],
)
print(columns)


city1  2010     100
       2020     200
city2  2010    1001
       2020    1002
dtype: int64
city   year
city1  2010     100
       2020     200
city2  2010    1001
       2020    1002
dtype: int64
MultiIndex([('city1', 2010),
            ('city1', 2020),
            ('city2', 2010),
            ('city2', 2020)],
           names=['city', 'year'])
MultiIndex([('person1', 'job1'),
            ('person1', 'job2'),
            ('person2', 'job1'),
            ('person2', 'job2'),
            ('person3', 'job1'),
            ('person3', 'job2')],
           names=['worker', 'job'])


In [18]:
rng = np.random.default_rng(1)
data = rng.random((4, 6))
print(data)

data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)

[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person1             person2             person3          
job             job1      job2      job1      job2      job1      job2
city  year                                                            
city1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
      2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
      2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


In [19]:
## 2. Из получившихся данных выбрать данные по 
# - 2020 году (для всех столбцов)
# - job_1 (для всех строк)
# - для city_1 и job_2 
index = pd.MultiIndex.from_product(
    [
        [
            "city1",
            "city2",
        ],
        [2010, 2020],
    ],
    names=["city", "year"],
)
columns = pd.MultiIndex.from_product(
    [
        [
            "person1",
            "person2",
            "person3",
        ],
        ["job1", "job2"],
    ],
    names=["worker", "job"],
)
rng = np.random.default_rng(1)
data = rng.random((4, 6))
data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)
# 2020 году (для всех столбцов)
print(data_df.loc[(slice(None), 2020), :])
# job1 (для всех строк)
print(data_df.xs("job1", level="job", axis=1))
# для city1 и job2
print(data_df.loc["city1"].xs("job2", level="job", axis=1))
# Или через .loc с сохранением MultiIndex
print(data_df.loc["city1", (slice(None), "job2")])

worker       person1             person2             person3          
job             job1      job2      job1      job2      job1      job2
city  year                                                            
city1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
      2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
      2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
worker       person1             person2             person3          
job             job1      job2      job1      job2      job1      job2
city  year                                                            
city1 2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city2 2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
worker       person1   person2   person3
city  year                              
city1 2010  0.511822  0.144160  0.311831
      2020  0.827703  0.5

In [20]:
# Индексация и срезы (по мультииндексу)

data = {
    ("city1", 2010): 100,
    ("city1", 2020): 200,
    ("city2", 2010): 1001,
    ("city2", 2020): 1002,
    ("city3", 2010): 10001,
    ("city3", 2020): 10002,
}
s = pd.Series(data)
s.index.names = ["city", "year"]
print(s)

city   year
city1  2010      100
       2020      200
city2  2010     1001
       2020     1002
city3  2010    10001
       2020    10002
dtype: int64


In [21]:
print(s["city1", 2010])
print(s["city1"])

100
year
2010    100
2020    200
dtype: int64


In [22]:
print(s.loc["city1":"city2"])
print(s[:, 2010])

city   year
city1  2010     100
       2020     200
city2  2010    1001
       2020    1002
dtype: int64
city
city1      100
city2     1001
city3    10001
dtype: int64


In [23]:
print(s[s > 2000])
print(s[["city1", "city3"]])

city   year
city3  2010    10001
       2020    10002
dtype: int64
city   year
city1  2010      100
       2020      200
city3  2010    10001
       2020    10002
dtype: int64


In [24]:
## 3. Взять за основу DataFrame со следующей структурой
# Выполнить запрос на получение следующих данных
# - все данные по person_1 и person_3
# - все данные по первому городу и первым двум person-ам (с использование срезов)
#
# Приведите пример (самостоятельно) с использованием pd.IndexSlice

index = pd.MultiIndex.from_product(
    [
        [
            "city1",
            "city2",
        ],
        [2010, 2020],
    ],
    names=["city", "year"],
)
columns = pd.MultiIndex.from_product(
    [
        [
            "person1",
            "person2",
            "person3",
        ],
        ["job1", "job2"],
    ],
    names=["worker", "job"],
)
rng = np.random.default_rng(1)
data = rng.random((4, 6))
data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)
# все данные по person1 и person3
print(data_df.loc[:, (["person1", "person3"], slice(None))])
# все данные по первому городу city1 и первым двум person'ам (с использованием срезов)
print(data_df.loc["city1", (["person1", "person2"], slice(None))])

worker       person1             person2             person3          
job             job1      job2      job1      job2      job1      job2
city  year                                                            
city1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
      2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
      2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
worker       person1             person3          
job             job1      job2      job1      job2
city  year                                        
city1 2010  0.511822  0.950464  0.311831  0.423326
      2020  0.827703  0.409199  0.753513  0.538143
city2 2010  0.329732  0.788429  0.134042  0.403113
      2020  0.203455  0.262313  0.485191  0.980737
worker   person1             person2          
job         job1      job2      job1      job2
year                                          
2010 

In [25]:
index = pd.MultiIndex.from_product(
    [
        [
            "city1",
            "city2",
        ],
        [2010, 2020],
    ],
    names=["city", "year"],
)
columns = pd.MultiIndex.from_product(
    [
        [
            "person1",
            "person2",
            "person3",
        ],
        ["job1", "job2"],
    ],
    names=["worker", "job"],
)
rng = np.random.default_rng(1)
data = rng.random((4, 6))
data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)
'''Допустим, мы хотим выбрать данные:
-Для city1 и city2 (все города)
-За 2020 год
-Для person2 и person3
-Только для job1'''
idx = pd.IndexSlice
print(data_df.loc[pd.IndexSlice[:, 2020], idx[["person2", "person3"], "job1"]])

worker       person1             person2             person3          
job             job1      job2      job1      job2      job1      job2
city  year                                                            
city1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
      2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
      2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
worker       person2   person3
job             job1      job1
city  year                    
city1 2020  0.549594  0.753513
city2 2020  0.750365  0.485191


In [26]:
# Перегруппировка мультииндексов

rng = np.random.default_rng(1)
index = pd.MultiIndex.from_product([["a", "c", "b"], [1, 2]])
data = pd.Series(rng.random(6), index=index)
data.index.names = ["char", "int"]
print(data)
# print(data['a':'b']) # Надо пересортировать
data = data.sort_index()
print(data)
print(data["a":"b"])

char  int
a     1      0.511822
      2      0.950464
c     1      0.144160
      2      0.948649
b     1      0.311831
      2      0.423326
dtype: float64
char  int
a     1      0.511822
      2      0.950464
b     1      0.311831
      2      0.423326
c     1      0.144160
      2      0.948649
dtype: float64
char  int
a     1      0.511822
      2      0.950464
b     1      0.311831
      2      0.423326
dtype: float64


In [27]:
index = [
    ("city1", 2010, 1),
    ("city1", 2010, 2),
    ("city1", 2020, 1),
    ("city1", 2020, 2),
    ("city2", 2010, 1),
    ("city2", 2010, 2),
    ("city2", 2020, 1),
    ("city2", 2020, 2),
    ("city3", 2010, 1),
    ("city3", 2010, 2),
    ("city3", 2020, 1),
    ("city3", 2020, 2),
]
population = [101, 1010, 201, 2010, 102, 1020, 202, 2020, 103, 1030, 203, 2030]
pop = pd.Series(population, index=index)
print(pop)
i = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(i)
print(pop)

(city1, 2010, 1)     101
(city1, 2010, 2)    1010
(city1, 2020, 1)     201
(city1, 2020, 2)    2010
(city2, 2010, 1)     102
(city2, 2010, 2)    1020
(city2, 2020, 1)     202
(city2, 2020, 2)    2020
(city3, 2010, 1)     103
(city3, 2010, 2)    1030
(city3, 2020, 1)     203
(city3, 2020, 2)    2030
dtype: int64
city1  2010  1     101
             2    1010
       2020  1     201
             2    2010
city2  2010  1     102
             2    1020
       2020  1     202
             2    2020
city3  2010  1     103
             2    1030
       2020  1     203
             2    2030
dtype: int64


In [28]:
print(pop.unstack())
print(pop.unstack(level=0))
print(pop.unstack(level=1))
print(pop.unstack(level=2))

              1     2
city1 2010  101  1010
      2020  201  2010
city2 2010  102  1020
      2020  202  2020
city3 2010  103  1030
      2020  203  2030
        city1  city2  city3
2010 1    101    102    103
     2   1010   1020   1030
2020 1    201    202    203
     2   2010   2020   2030
         2010  2020
city1 1   101   201
      2  1010  2010
city2 1   102   202
      2  1020  2020
city3 1   103   203
      2  1030  2030
              1     2
city1 2010  101  1010
      2020  201  2010
city2 2010  102  1020
      2020  202  2020
city3 2010  103  1030
      2020  203  2030


In [29]:
# NumPy конкатенация

x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
print(np.concatenate([x, y, z]))
x = [[1, 2, 3]]
y = [[4, 5, 6]]
z = [[7, 8, 9]]
print(np.concatenate([x, y, z], axis=0))
print(np.concatenate([x, y, z], axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [30]:
# Pandas - concat

ser1 = pd.Series(["a", "b", "c"], index=[1, 2, 3])
ser2 = pd.Series(["d", "e", "f"], index=[4, 5, 6])
print(pd.concat([ser1, ser2]))
ser1 = pd.Series(["a", "b", "c"], index=[1, 2, 3])
ser2 = pd.Series(["d", "e", "f"], index=[4, 5, 6])
print(pd.concat([ser1, ser2], verify_integrity=False))  # Для уникальности индексов
print(pd.concat([ser1, ser2], ignore_index=True))  # Для игнора индексов
print(pd.concat([ser1, ser2], keys='["x", "y"]'))  # Добавляет еще индексы
ser1 = pd.Series(["a", "b", "c"], index=[1, 2, 3])
ser2 = pd.Series(["b", "c", "f"], index=[4, 5, 6])
print(pd.concat([ser1, ser2], join='outer'))  
print(pd.concat([ser1, ser2], join="inner"))  

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
0    a
1    b
2    c
3    d
4    e
5    f
dtype: object
[  1    a
   2    b
   3    c
"  4    d
   5    e
   6    f
dtype: object
1    a
2    b
3    c
4    b
5    c
6    f
dtype: object
1    a
2    b
3    c
4    b
5    c
6    f
dtype: object


C:\Users\Nikita\AppData\Local\Temp\ipykernel_8296\1538061734.py:10: FutureWarning: The behavior of pd.concat with len(keys) != len(objs) is deprecated. In a future version this will raise instead of truncating to the smaller of the two sequences
  print(pd.concat([ser1, ser2], keys='["x", "y"]'))  # Добавляет еще индексы


In [31]:
## 4. Привести пример использования inner и outer джойнов для Series (данные примера скорее всего нужно изменить)

ser1 = pd.Series(["a", "b", "c", "f"], index=[1, 2, 3, 4])
ser2 = pd.Series(["b", "c", "f"], index=[4, 5, 6])
# outer по умолчанию
print(pd.concat([ser1, ser2], axis=1, join="outer"))
print()
# inner устанавливает пересечение
print(pd.concat([ser1, ser2], axis=1, join="inner"))

     0    1
1    a  NaN
2    b  NaN
3    c  NaN
4    f    b
5  NaN    c
6  NaN    f

   0  1
4  f  b
